services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${RUNNING_PORT}:${RUNNING_PORT}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    links:
      - db
    environment:
      - DBMS=postgres

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:${POSTGRES_PORT} -t 30s -i 250ms

  db:
    image: postgres:alpine3.18
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}